### ISSUE TITLE
A question regarding the Ecster payment confirmation email

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#14]
We noticed that the order reference in the payment confirmation email sent by Ecster is not the Magento order number when the customer pays with Swish. 

Example for a Swish payment:
![image](https://user-images.githubusercontent.com/25124716/100499525-9e79aa00-316a-11eb-899c-21508730fd03.png)

Example for a Card payment:
![image](https://user-images.githubusercontent.com/25124716/100499540-c537e080-316a-11eb-805b-f69428452f78.png)

It seems to be an internal Ecster reference instead. 
This could be due to the nature of Swish payments, where payment is done before the order is created in Magento. Delaying these emails for say 20-30 seconds could maybe solve this problem, just a thought. From the customer point of view, it would be better to always get the Magento order number for reference.

**Comment by TobiasLufinity** [comment]
You are correct, it's the way the Swish payments are made.
Ecster debit the payment instantly and because Magento creates the order after the customer is redirected to the success page the ordernumber is not yet created. It might be able to be fixed to send the reserved order ID to Ecster which is set on the quote.

I will take a look at this during next week.

**Comment by TobiasLufinity** [comment]
In order to fix this issue we will need a new event when a Customer click "Submit Order" which is under development in Ecster. After that we can hook onto that event and reserve an order id which then will be sent to Ecster so the email will have the correct id of the not yet created order.

Waiting for response from Ecster

**Comment by TobiasLufinity** [comment]
A order id reservation is now made earlier in the checkout flow to battle this issue.

This might affect the order number sequence though as it's now more likely to be jumps in order number when customers payments might fail and they decide to abandon the cart. Unfortunately there is no good way around this and still have this function.
The only fix would be for Ecster to wait to send out the confirmation email until the order is created and we have no power over that.

Please upgrade to version 1.0.8 for this fix
