### ISSUE TITLE
Issue in checkout page with the VAT

### ISSUE THREAD

**Issue by nitesh0612** [evalentgroup/Magento-2-Ecster-Pay#17]
Hello Team,

Please check the attached file with the issue and let me know if you people help us on this. 

Regards
Nitesh

[ecster functionality feedback from ATV v1.docx](https://github.com/evalentgroup/Magento-2-Ecster-Pay/files/6082447/ecster.functionality.feedback.from.ATV.v1.docx)

**Comment by TobiasLufinity** [comment]
Module version 1.0.10 includes fixes for this issue. Please update the module in your store.

**Comment by nitesh0612** [comment]
After update the module getting this error message. Please check the attached screen shot below. 

![Skärmavbild 2021-03-08 kl  12 01 46](https://user-images.githubusercontent.com/48681088/110313646-bf388200-802c-11eb-833a-4d43d3402201.png)

**Comment by TobiasLufinity** [comment]
This was due to a type declaration which is only supported in later PHP version.
I removed this in the latest version 1.0.11. Please update and try again

**Comment by nitesh0612** [comment]
Now getting this error message while going to checkout page. Please check attached screen shot for your reference. 
![paymet](https://user-images.githubusercontent.com/48681088/110317955-e1350300-8032-11eb-92b5-60f465a1074e.png)

**Comment by TobiasLufinity** [comment]
This means that there was no shipping method activated for the country so the checkout throws an error and sends you back to checkout/cart.

**Comment by nitesh0612** [comment]
Before update the module everything is working.

**Comment by TobiasLufinity** [comment]
Did you back the update because I managed to get to the checkout  on you site
![Screenshot from 2021-03-08 13-26-05](https://user-images.githubusercontent.com/32361984/110321370-e0d84000-8011-11eb-8d4b-4d19b9fd7dde.png)

And this function which causes the exception has not been modified in any of the later versions of the module.

**Comment by nitesh0612** [comment]
No, we didn't downgrade the code version. Just commented the Exception

if (!$this->isShippingMethods()) {
                 //   throw new \Exception(__(
                        "We could not find a valid delivery method for %1. Please contact the site administration.",
                        $this->ecsterPayHelper->getCountryName(!is_null($this->getAddress()->getCountryId()) ? $this->getAddress()->getCountryId() : $this->ecsterPayHelper->getDefaultCountry($storeId))
                    ));
                }

**Comment by TobiasLufinity** [comment]
I can't replicate the issue on our stage server. What shipping method are you using? Do you have an external shipping module?
If so, it might be an compatibility issue between these two modules.

**Comment by nitesh0612** [comment]
Can you check from our admin panel if I provide you the access ?

**Comment by TobiasLufinity** [comment]
Yes, I can take a look. You cans end the info to tobias.nilsson@evalent.com

**Comment by nitesh0612** [comment]
Sent. Please check once.

**Comment by TobiasLufinity** [comment]
I see you are using WebShopApps Matrix Rate for your shipment which is a third party module which have not been taking in consideration when building the module.

The issue is that we look through all shipping methods and see that there is an available method for the default country but Matrix Rate does this in a later stage than Magento and thus we can't see that it's available.

I think it's best to just ignore this check because if you arrive to the checkout you will get a message that there is no available methods anyways.

I will check if there is more to it otherwise I will remove it in the next release. But for now keep it commented til I have time to fix it.
